### PR TITLE
Feature: Update Profile-related rejections

### PR DESCRIPTION
**Pull request by YehorPytomets**
In this PR we introduce rejections, that may be raised when handling the commands of the `ProfileAggregate`.
We redefine profile statuses to `PUBLISHED` and `NOT_PUBLISHED` and renamed some commands to reflect the profile status changes:
  - The profile cannot now be revoked because of ambiguity if the term _revoke_. But, it can now be marked as not published, given the published profile: `RevokeProfile` -> `MarkProfileAsNotPublished`;
  - The same is for _restoring from revoked_. Now we publish the profile instead: `RestoreProfileFromRevoked` -> `PublishProfile`.

Also, rename:
- `ProfileRestoredFromRemoved` -> `ProfileRestored`;
- `QualificationProfileStatus` -> `ProfileStatus`.

### CODE REVIEW

**Comment by armiol** [comment]
@YehorPytomets please find a better term than `REVOKED`. One is able to revoke smth previously granted. That's not the case what we've got with `Profile`.

**Comment by YehorPytomets** [comment]
@armiol , I've found another term, that I feel may well be a good substitute: `SUSPENDED`. That is put to stop working or being active temporarily. We usually suspend licenses or, better say, subscriptions to online services. Can we say the same about `Profile`?

**Comment by YehorPytomets** [comment]
@armiol , statuses of the profile are changed according to the discussion. Related signals are renamed or removed. PR is ready to review.

**Comment by YehorPytomets** [comment]
@armiol , the PR was updated according to the discussion and is ready to review.

**Pull request merged**
